spring:
  application:
    name: word-svc
---
logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: WARN
    com.ibt.vocab.word: DEBUG
    org.springframework: WARN
  # datasource:
  #   url: jdbc:mysql://localhost:3306/myDatabase
  #   username: root
  #   password: 12345